src/directive/angular-echarts.directive.ts

I'm reusing the charts for different datasets.
This works fine as long as all data is replaced. Unreplaced datasets will stay in the new chart. 
Clearing the chart resolves this issue for me and could be useful for others as well.

Expose Clear Function

---

src/directive/angular-echarts.directive.ts

if we update '[options] = {}' run resetChart
- add private resetChart funtion
- fix onOptionsChange
I read this echart github question and change it.
https://github.com/ecomfe/echarts/issues/2387
We can update empty data chart or remove old result chart data.

Add resetChart function

---

lib/src/directive/ngx-echarts.directive.ts

I'm working on an app where the chart auto-resize feature is conflicting with the rendering of other components when toggling from/to fullscreen view. 
I'd like to be  able to control whether or not this auto-resize feature is activated.
I propose to add an 'autoResize' input in NgxEchartsDirective, controlling the activation of the auto-resize feature triggered by a window resize event.
Of course, by default, the automatic resize feature is activated (autoResize = true).

New input to control activation/deactivation of chart auto-resize feature

---

README.md
angular.json
package.json
projects/ngx-echarts/package.json
projects/ngx-echarts/src/lib/ngx-echarts.directive.ts
projects/ngx-echarts/src/lib/ngx-echarts.service.ts
src/app/views/usage/events/events.component.ts
src/main.ts
tsconfig.json
yarn.lock

a follow-up of #124 
The following is copied from original PR: 
This is definitely not a final pull request, more like a POC.
1. The `main.ts` probably needs to be reworked to use ES6 imports for all the libraries
2. The documentation needs to be updated to not assume to have the global `echarts`
3. Examples should be updated as well
4. Webpack / systemjs setup probably need to be adapted as well
5. Other minor fixes?
Ideas for the future:
1. Deprecate a half of the ngxechartsservice methods as long as the original library's exports could be used instead
2. Other?
The aot build requires minified version in tsconfig paths, see https://github.com/apache/incubator-echarts/issues/8493#issuecomment-401850374

feat(usability): added typings and moved the angular cli configuration to the tsconfig.json

---

projects/ngx-echarts/src/lib/echart-events.ts
projects/ngx-echarts/src/lib/ngx-echarts.directive.ts

In order to work with these events, the chart map series 'selectedMode' must be set to either 'single' or 'multiple'.

Add map events support to echarts directive

---

package.json

The base package lacks a license. A MIT license helps automated software
auditing.
Close the PR if not applicable.

Add MIT license to 'ngx-echarts-demo'

---

projects/ngx-echarts/src/lib/ngx-echarts.directive.ts

when compling a project which using rollup, an error occurred: "init is not defined"

fix 'init is not defined' error when using rollup complie.

---

projects/ngx-echarts/src/lib/ngx-echarts.directive.ts

Reverts xieziyu/ngx-echarts#190

Revert "fix 'init is not defined' error when using rollup complie."

---

README.md
projects/ngx-echarts/src/lib/ngx-echarts.directive.ts

Add support for [brushEnd](https://echarts.apache.org/en/api.html#events.brushEnd) event introduced in echarts v4.5.0

Add output for brushEnd event

---

README.md
projects/ngx-echarts/src/lib/ngx-echarts.directive.ts

Hi @xieziyu 
I did not bother you for a long time, it's time to do this again :)
The new way of importing the echarts is very heavy, because it loads the whole echarts in the application right away; however in most of my projects the echarts is a helper library which appears on several secondary pages.
Even if you make a custom build, it's still 170K gzipped which needs to be downloaded and parsed => performance goes down.
This PR aims this issue.
Actually I wanted to use this approach for protobuf `Any` data type at my https://github.com/ngx-grpc/ngx-grpc for a long time and always didn't have this time to implement it. So, sorry, but looks like we need to test it with ngx-echarts :)
The change is not breaking, and to use all its goodness one just need to change the imports in …

Allow loading echarts library lazily via native import

---

projects/ngx-echarts/src/lib/ngx-echarts.module.ts

Not tested but should resolve https://github.com/xieziyu/ngx-echarts/issues/250
See this for more info https://angular.io/guide/migration-module-with-providers

Fix Angular 10 generic ModuleWithProviders depreciation

---

projects/ngx-echarts/src/lib/ngx-echarts.module.ts

我这里希望能以 shared.module.ts 的方式安装。
写出来大致是这个样子
```ts
import { NgxEchartsModule, NGX_ECHARTS_CONFIG } from 'ngx-echarts';
import * as echarts from 'echarts'; 
@NgModule({
imports: [
NgxEchartsModule,
],
exports: [
NgxEchartsModule,
],
providers: [
{ provide: NGX_ECHARTS_CONFIG, useValue: echarts },
],
})
export class SharedModule { }
```
能麻烦把这个选项 export 出来么？

Export NGX_ECHARTS_CONFIG

---

README.md

* Fix typos such as 'porpeties', 'extentions', 'intance', and so on.
* Update references to ECharts documentation to the updated Apache project (older links are now dead).
* A few small bits of rephrasing and grammatical changes to sound more natural.

Fix typos and grammar in README file

---

projects/ngx-echarts/src/lib/ngx-echarts.directive.ts

The error occurred quite often, so I referenced other repo and modified code.
Hope it helps!
Reference:
https://github.com/WICG/resize-observer/issues/38
https://github.com/airbnb/visx/pull/335

fix: avoid "ResizeObserver loop limit exceeded" error

---

projects/ngx-echarts/src/lib/ngx-echarts.directive.ts

This prevents multiple attempts to dispose a chart if it already has been disposed.  This will prevent the display of Echarts warning message.

Guard dispose

---

src/app/pages/welcome/welcome.component.html

As I mentioned here: https://github.com/xieziyu/ngx-echarts/issues/314
The welcome page seems to be missing installation steps

Add missing resize-observer steps in welcome bash installation code

---

README.md
projects/ngx-echarts/src/lib/ngx-echarts.directive.ts

你好 Ziyu Xie，
I was facing some problems do change my graphs locale and I tried to follow the instructions provided in https://github.com/xieziyu/ngx-echarts/issues/290, but I had no success to change the locale. So in a further [investigation](https://jsfiddle.net/ydac567f/) with echarts package I found that is needed to register the built-in or custom location object and also change the chart locale option.
So to achieve this I added to `initOpts` the `locale` property and add a change locale section in README.
谢谢!

Add initOpts locale property and update README

---

README.md
projects/ngx-echarts/package.json
projects/ngx-echarts/src/lib/ngx-echarts.module.ts

fix: missing NgxEchartsModule.forChild return type

---

projects/ngx-echarts/src/lib/ngx-echarts.directive.ts
projects/ngx-echarts/src/lib/ngx-echarts.module.ts

Add `theme` in `NgxEchartsConfig`. Can use `provideEcharts({ theme: 'your-theme' })` or `provideEchartsCore({ echarts, theme: 'your-theme' })` to specify the default theme, when using ngx-echarts but leave `[theme]` empty, echarts will get theme from config.

feat: support default theme for all chart instances

---

projects/ngx-echarts/src/lib/ngx-echarts.directive.ts

It was hard for me to find out, which type of object is emitted by the `chartInit` event emitter. So I think it would be a better dev experience to set it explicit to `ECharts` instead of  `any`.

feat: add chartInit EventEmitter type
